img_agents =  {
        "0": 'https://valorantinfo.com/images/es/tarjeta-de-astra-de-valorant_valorant_art_10694.webp',
        "1": 'https://valorantinfo.com/images/us/valorant-breach-card_valorant_art_9971.webp',
        "2": 'https://valorantinfo.com/images/us/valorant-brimstone-card_valorant_art_9973.webp',
        "3": 'https://valorantinfo.com/images/es/tarjeta-de-chamber-de-valorant_valorant_art_10676.webp',
        "4": 'https://valorantinfo.com/images/us/valorant-cypher-card_valorant_art_9975.webp',
        "5": 'https://valorantinfo.com/images/es/tarjeta-de-fade-de-valorant_valorant_art_36429.webp',
        "6": 'https://valorantinfo.com/images/us/valorant-gekko-card_valorant_art_50037.webp',
        "7": 'https://valorantinfo.com/images/es/tarjeta-de-harbor-de-valorant_valorant_art_44465.webp',
        "8": 'https://valorantinfo.com/images/us/valorant-jett-card_valorant_art_9983.webp',
        "9": 'https://valorantinfo.com/images/es/tarjeta-de-kayo-de-valorant_valorant_art_10678.webp',
        "10": 'https://valorantinfo.com/images/us/valorant-killjoy-card_valorant_art_9986.webp',
        "11": 'https://valorantinfo.com/images/us/valorant-neon-card_valorant_art_10001.webp',
        "12": 'https://valorantinfo.com/images/us/valorant-omen-card_valorant_art_9987.webp',
        "13": 'https://valorantinfo.com/images/us/valorant-phoenix-card_valorant_art_9989.webp',
        "14": 'https://valorantinfo.com/images/us/valorant-raze-card_valorant_art_9991.webp',
        "15": 'https://valorantinfo.com/images/us/valorant-reyna-card_valorant_art_9993.webp',
        "16": 'https://valorantinfo.com/images/us/valorant-sage-card_valorant_art_9997.webp',
        "17": 'https://valorantinfo.com/images/us/valorant-skye-card_valorant_art_9981.webp',
        "18": 'https://valorantinfo.com/images/us/valorant-sova-card_valorant_art_9999.webp',
        "19": 'https://valorantinfo.com/images/us/valorant-viper-card_valorant_art_10005.webp',
        "20": 'https://valorantinfo.com/images/us/valorant-yoru-card_valorant_art_10003.webp',   
    }